services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8282:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=1024m
    
volumes:
  nexus_data:
