services:
  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    restart: always
    environment:
      - IMGPROXY_PROMETHEUS_BIND=:9000
    ports:
      - 10001:8080
      - 10000:9000
