{
 "title": "imgproxy instrumentation",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests rate (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(requests_total{job=\"$application\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors count by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(errors_total{job=\"$application\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"$application\"}[1m]))\n/\nsum(rate(request_duration_seconds_count{job=\"$application\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(processing_duration_seconds_sum{job=\"$application\"}[1m]))\n/\nsum(rate(processing_duration_seconds_count{job=\"$application\"}[1m]))",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum(rate(download_duration_seconds_sum{job=\"$application\"}[1m]))\n/\nsum(rate(download_duration_seconds_count{job=\"$application\"}[1m]))",
     "legendFormat": "Downloading"
    }
   ]
  },
  {
   "title": "95% response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{job=\"$application\"}[1m])) by (le)) ",
     "legendFormat": "Total"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(processing_duration_seconds_bucket{job=\"$application\"}[1m])) by (le)) ",
     "legendFormat": "Processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(download_duration_seconds_bucket{job=\"$application\"}[1m])) by (le)) ",
     "legendFormat": "Downloading"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=\"$application\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=\"$application\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (process_resident_memory_bytes{job=\"$application\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (process_resident_memory_bytes{job=\"$application\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (go_memstats_sys_bytes{job=\"$application\"})",
     "legendFormat": "Sys"
    },
    {
     "expr": "sum (go_memstats_heap_inuse_bytes{job=\"$application\"})",
     "legendFormat": "HeapInUse"
    },
    {
     "expr": "sum (go_memstats_heap_idle_bytes{job=\"$application\"})",
     "legendFormat": "HeapIdle"
    }
   ]
  },
  {
   "title": "Vips memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vips_memory_bytes{job=\"$application\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(vips_max_memory_bytes{job=\"$application\"})",
     "legendFormat": "Highwater"
    }
   ]
  },
  {
   "title": "Vips allocs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vips_allocs{job=\"$application\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg buffer size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(buffer_size_bytes_sum{job=\"$application\"}[1m])) by (type)\n/\nsum(increase(buffer_size_bytes_count{job=\"$application\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Buffers calibration stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(buffer_default_size_bytes{job=\"$application\"}) by (type)",
     "legendFormat": "default of {{type}}"
    },
    {
     "expr": "max(buffer_max_size_bytes{job=\"$application\"}) by (type)",
     "legendFormat": "max of {{type}}"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"$application\"})",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "sum(go_threads{job=\"$application\"})",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}