{
 "title": "kmq",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue counter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Metric by queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "queue_counter_by_queue", "legendFormat": "{{queue_name}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "rate(queue_counter_by_queue[1m])",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(grpc_server_processing_duration_seconds_sum[1m]) / rate(grpc_server_processing_duration_seconds_count[1m])",
     "legendFormat": "{{method}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "gRPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(grpc_server_processing_duration_seconds_count[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}