services:

  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /opt/registry/data:/var/lib/registry
    networks:
      - registry_network

  registry-manager:
    image: snagles/docker-registry-manager
    container_name: docker-registry-manager
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./registries.yml:/app/registries.yml
      #- ./ssl.crt:/app/ssl.crt # https certfile location
      #- ./ssl.key:/app/ssl.key # https keyfile location
    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
      #- MANAGER_ENABLE_HTTPS=true
      #- MANAGER_KEY=/app/ssl.crt
      #- MANAGER_CERTIFICATE=/app/ssl.key
    depends_on:
      - registry
    networks:
      - registry_network

networks:
  registry_network:
