scrape_configs:
  # - job_name: some-service
  #   metrics_path: "actuator/prometheus"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [1.1.1.1:84]
  - job_name: postgres-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.31.117:9187]
  - job_name: redis-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.31.117:9121]
