scrape_configs:
  # - job_name: some-service
  #   metrics_path: "actuator/prometheus"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [1.1.1.1:84]
  - job_name: postgres-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:9187]
  - job_name: redis-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:9121]
  - job_name: site-counter-core
    metrics_path: "actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:8001]
  - job_name: site-counter-collector
    metrics_path: "actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:8100]
  - job_name: kmq
    metrics_path: "actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:8484]
  - job_name: nio-postgres-kafka-connect
    metrics_path: "actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:8380]
  - job_name: imgproxy
    scrape_interval: 5s
    static_configs:
      - targets: [192.168.10.136:10000]
