services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./music:/music #optional
      - ./downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
