services:

  minio1:
    image: minio/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
      # - MINIO_OPTS="--console-address :9001"
    ports:
      # console
      - 9003:9001
      # api
      - 9004:9000
    networks:
      - minio_net
    volumes:
      - minio_volume_local:/data1:rw
      - /media/minio:/data2:rw
    command: server --console-address ":9001" http://minio{1...2}/data{1...2}

  minio2:
    image: minio/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
    networks:
      - minio_net
    volumes:
      - minio_volume_local_2:/data1:rw
      - minio_volume_local_3:/data2:rw
    command: server --console-address ":9001" http://minio{1...2}/data{1..2}

networks:
  minio_net:

volumes:
  minio_volume_local:
  minio_volume_local_2:
  minio_volume_local_3: