services:

  postgres:
    image: postgres:latest
    container_name: postgres-common
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tester -d tester" ]
      interval: 5s
      timeout: 1s
      retries: 100
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester
      - POSTGRES_DB=tester
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
