services:

  redis:
    image: redis:latest
    container_name: redis-common
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    mem_limit: 128m
    healthcheck:
      test: redis-cli ping || exit 1
    command: redis-server --save 60 1

volumes:
  redis-volume:
